---
# tasks file for proxied role

- name: Create /root/bin
  when: PublicVpc | bool
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create /root/bin/install-proxyCACert.sh
  when: PublicVpc | bool
  template:
    src:   root/bin/install-proxyCACert.sh
    dest: /root/bin/install-proxyCACert.sh
    backup: yes
    mode: 0700
    owner: root
    group: root
    force: yes

- name: Create /etc/pki/ca-trust/source/anchors/proxyCA.pem
  when: PublicVpc | bool
  shell:
    creates: /etc/pki/ca-trust/source/anchors/proxyCA.pem
    cmd: /root/bin/install-proxyCACert.sh

- name: Create /etc/profile.d/proxy.csh
  when: PublicVpc | bool
  template:
    src:   etc/profile.d/proxy.csh
    dest: /etc/profile.d/proxy.csh
    backup: yes
    mode: 0644
    owner: root
    group: root
    force: yes

- name: Create /etc/profile.d/proxy.sh
  when: PublicVpc | bool
  template:
    src:   etc/profile.d/proxy.sh
    dest: /etc/profile.d/proxy.sh
    backup: yes
    mode: 0644
    owner: root
    group: root
    force: yes

- name: Create /etc/yum.repos.d/10_proxy.conf
  when: PublicVpc | bool
  template:
    src:   etc/yum.repos.d/10_proxy.conf
    dest: /etc/yum.repos.d/10_proxy.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
    force: yes
